response_context = ['ATTRS', '__aenter__', '__aexit__', '__annotations__', '__class__', '__del__', '__delattr__',
                    '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__',
                    '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__',
                    '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__',
                    '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_body', '_cache', '_cleanup_writer',
                    '_closed', '_connection', '_content_dict', '_content_type', '_continue', '_headers', '_history',
                    '_loop', '_notify_content', '_parse_content_type', '_protocol', '_raw_headers', '_real_url',
                    '_released', '_request_info', '_resolve_charset', '_response_eof', '_session', '_source_traceback',
                    '_stored_content_type', '_timer', '_traces', '_url', '_writer', 'charset', 'close', 'closed',
                    'connection', 'content', 'content_disposition', 'content_length', 'content_type', 'cookies',
                    'get_encoding', 'headers', 'history', 'host', 'json', 'links', 'method', 'ok', 'raise_for_status',
                    'raw_headers', 'read', 'real_url', 'reason', 'release', 'request_info', 'start', 'status', 'text',
                    'url', 'url_obj', 'version', 'wait_for_close']
